// This file is generated by CMake. Do not edit it manually!

#include <cstdint>

namespace V2MPAsm
{
	static constexpr int32_t VERSION_MAJOR = 1;
	static constexpr int32_t VERSION_MINOR = 0;
	static constexpr int32_t VERSION_PATCH = 0;
	static constexpr const char* const VERSION_STRING = "1.0.0";
	static constexpr const char* const BUILD_IDENTIFIER_STRING = "5de8f7d";
}
