// This file is generated by CMake. Do not edit it manually!

#include "LibV2MPLink/Version.h"
#include "Interface_Version.gen.h"

LIBV2MPLINK_PUBLIC(int32_t) V2MPLink_Version_GetMajor(void)
{
	return V2MPLink::VERSION_MAJOR;
}

LIBV2MPLINK_PUBLIC(int32_t) V2MPLink_Version_GetMinor(void)
{
	return V2MPLink::VERSION_MINOR;
}

LIBV2MPLINK_PUBLIC(int32_t) V2MPLink_Version_GetPatch(void)
{
	return V2MPLink::VERSION_PATCH;
}

LIBV2MPLINK_PUBLIC(const char*) V2MPLink_Version_GetVersionString(void)
{
	return V2MPLink::VERSION_STRING;
}

LIBV2MPLINK_PUBLIC(const char*) V2MPLink_Version_GetBuildIdentifier(void)
{
	return V2MPLink::BUILD_IDENTIFIER_STRING;
}
