// This file is generated by CMake. Do not edit it manually!

#include "LibV2MPLink/Version.h"
#include "Interface_Version.gen.h"

extern "C"
{
	API_LIBV2MPLINK int32_t V2MPLink_Version_GetMajor(void)
	{
		return V2MPLink::VERSION_MAJOR;
	}

	API_LIBV2MPLINK int32_t V2MPLink_Version_GetMinor(void)
	{
		return V2MPLink::VERSION_MINOR;
	}

	API_LIBV2MPLINK int32_t V2MPLink_Version_GetPatch(void)
	{
		return V2MPLink::VERSION_PATCH;
	}

	API_LIBV2MPLINK const char* V2MPLink_Version_GetVersionString(void)
	{
		return V2MPLink::VERSION_STRING;
	}

	API_LIBV2MPLINK const char* V2MPLink_Version_GetBuildIdentifier(void)
	{
		return V2MPLink::BUILD_IDENTIFIER_STRING;
	}
} // extern "C"
