#ifndef V2MPASM_TOKENS_TOKENMETA_PREPROCESSOR_H
#define V2MPASM_TOKENS_TOKENMETA_PREPROCESSOR_H

#include "Tokens/TokenMeta.h"

extern const V2MPAsm_TokenMeta V2MPAsm_TokenMeta_Preprocessor;

#endif // V2MPASM_TOKENS_TOKENMETA_PREPROCESSOR_H
