#ifndef V2MPASM_TOKENS_TOKENMETA_MULTILINECOMMENT_H
#define V2MPASM_TOKENS_TOKENMETA_MULTILINECOMMENT_H

#include "Tokens/TokenMeta.h"

extern const V2MPAsm_TokenMeta V2MPAsm_TokenMeta_MultilineComment;

#endif // V2MPASM_TOKENS_TOKENMETA_MULTILINECOMMENT_H
