name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build and run unit tests on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build and install unit tests
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DCMAKE_INSTALL_PREFIX=build/install -DBUILD_SHARED_LIBS=NO -DBUILD_TESTING=YES
        run-test: true
        ctest-options: -j8 --output-on-failure
        install-build: false
        parallel: 14
