name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build and run unit tests on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build and install unit tests
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DCMAKE_INSTALL_PREFIX="${{runner.workspace}}/build/install" -DBUILD_SHARED_LIBS=NO -DBUILD_TESTS=YES
        # TODO: We should get the unit testst to run with ctest, I've not used it before
        # run-test: true
        # ctest-options: -R mytest
        install-build: true
        parallel: 14
    - name: Run unit tests
      run: "${{runner.workspace}}/build/install/V2MP_Tests/bin/V2MP_Tests"
