name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build and run unit tests on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Build and run unit tests
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DBUILD_TESTING=YES
        run-test: true
        ctest-options: -j8 --output-on-failure
        install-build: false
        parallel: 14

  build-windows:
    name: Build and run unit tests on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build and run unit tests
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{runner.workspace}}/build
        cc: cl
        cxx: cl
        build-type: Release
        configure-options: -DBUILD_TESTING=YES
        run-test: true
        ctest-options: -j8 --output-on-failure
        install-build: false
        parallel: 14
